# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('website', models.URLField()),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField()),
                ('isCancelled', models.BooleanField(default=False)),
                ('isVisible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('website', models.URLField()),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField()),
                ('isCancelled', models.BooleanField(default=False)),
                ('isVisible', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Event'),
        ),
        migrations.AddField(
            model_name='activity',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
