# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'permissions': (('view_hidden_activity', 'Can see a hidden Activity'),)},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('view_hidden_event', 'Can see a hidden event'),)},
        ),
        migrations.AlterField(
            model_name='event',
            name='date_begin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateField(),
        ),
    ]
